/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlgorithmVisualizer: typeof import('./components/visualizer/AlgorithmVisualizer.vue')['default']
    AppFooter: typeof import('./components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    ArrayVisualizer: typeof import('./components/visualizer/ArrayVisualizer.vue')['default']
    Badge: typeof import('./components/ui/Badge.vue')['default']
    Button: typeof import('./components/ui/Button.vue')['default']
    Card: typeof import('./components/ui/Card.vue')['default']
    CardContent: typeof import('./components/ui/CardContent.vue')['default']
    CardDescription: typeof import('./components/ui/CardDescription.vue')['default']
    CardHeader: typeof import('./components/ui/CardHeader.vue')['default']
    CardTitle: typeof import('./components/ui/CardTitle.vue')['default']
    CodeEditor: typeof import('./components/editor/CodeEditor.vue')['default']
    CodeRunner: typeof import('./components/editor/CodeRunner.vue')['default']
    CodeSnippet: typeof import('./components/editor/CodeSnippet.vue')['default']
    Dialog: typeof import('./components/ui/Dialog.vue')['default']
    DifficultyBadge: typeof import('./components/content/DifficultyBadge.vue')['default']
    GraphVisualizer: typeof import('./components/visualizer/GraphVisualizer.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Input: typeof import('./components/ui/Input.vue')['default']
    LanguageSelector: typeof import('./components/editor/LanguageSelector.vue')['default']
    LanguageTabs: typeof import('./components/content/LanguageTabs.vue')['default']
    LinkedListVisualizer: typeof import('./components/visualizer/LinkedListVisualizer.vue')['default']
    MarkdownRenderer: typeof import('./components/content/MarkdownRenderer.vue')['default']
    MermaidDiagram: typeof import('./components/diagram/MermaidDiagram.vue')['default']
    Progress: typeof import('./components/ui/Progress.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollArea: typeof import('./components/ui/ScrollArea.vue')['default']
    Separator: typeof import('./components/ui/Separator.vue')['default']
    Skeleton: typeof import('./components/ui/Skeleton.vue')['default']
    SortingVisualizer: typeof import('./components/visualizer/SortingVisualizer.vue')['default']
    StackQueueVisualizer: typeof import('./components/visualizer/StackQueueVisualizer.vue')['default']
    StepController: typeof import('./components/visualizer/StepController.vue')['default']
    Table: typeof import('./components/ui/Table.vue')['default']
    Tabs: typeof import('./components/ui/Tabs.vue')['default']
    TabsContent: typeof import('./components/ui/TabsContent.vue')['default']
    TabsList: typeof import('./components/ui/TabsList.vue')['default']
    TabsTrigger: typeof import('./components/ui/TabsTrigger.vue')['default']
    Tooltip: typeof import('./components/ui/Tooltip.vue')['default']
    TopicCard: typeof import('./components/content/TopicCard.vue')['default']
    TreeVisualizer: typeof import('./components/visualizer/TreeVisualizer.vue')['default']
  }
}
